version: '3.8'

services:
  # API Gateway (Nginx)
  api-gateway:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - data-service
      - valuation-service
      - user-service
      - report-service

  # Backend services
  data-service:
    build:
      context: ./services/data_service
    volumes:
      - ./services/data_service:/app
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/valuecompass
      - ENVIRONMENT=development

  valuation-service:
    build:
      context: ./services/valuation_service
    volumes:
      - ./services/valuation_service:/app
    expose:
      - "8000"
    depends_on:
      - db
      - data-service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/valuecompass
      - DATA_SERVICE_URL=http://data-service:8000
      - ENVIRONMENT=development

  user-service:
    build:
      context: ./services/user_service
    volumes:
      - ./services/user_service:/app
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/valuecompass
      - JWT_SECRET=development_secret_key
      - ENVIRONMENT=development

  report-service:
    build:
      context: ./services/report_service
    volumes:
      - ./services/report_service:/app
    expose:
      - "8000"
    depends_on:
      - db
      - data-service
      - valuation-service
      - user-service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/valuecompass
      - DATA_SERVICE_URL=http://data-service:8000
      - VALUATION_SERVICE_URL=http://valuation-service:8000
      - USER_SERVICE_URL=http://user-service:8000
      - ENVIRONMENT=development

  # Frontend
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    environment:
      - API_URL=http://localhost:8000

  # Database
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=valuecompass
    ports:
      - "5432:5432"

volumes:
  postgres_data: